import {
  UserProfile,
  DailyQuest,
  InventoryItem,
  Recipe,
  EnergyTimeNode,
  ScheduleEvent,
  ChatMessage,
  TelemetryEvent,
  PrivacySetting
} from './types';

export const INITIAL_USER: UserProfile = {
  name: 'Maya',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCGrXBvtYz6w17RZ2_Fu-SffHzdS_N2LouOJQjz2AjLEEmA6uHs0qu3-49lJRBzxztcksXqOkyUD1reXS6-Zs-k9Hv7ZQNw6A0Zjq9A-KONiTw48BydI-dRHC0_qzrhDtklIaEw4dpg3DUoO5xU0WwQsyKeEQ7phMs6YZeTxcjJX9_pA--888_WdHKVkdKoH_VtC2A8makMNFwKnS5lcDsG4BCY-gefCgpwriurP9WVHqrRcpWFB2Muw',
  level: 3,
  xp: 420,
  xpTarget: 600,
  streakDays: 5,
  energyScore: 84,
  healthIndex: 78,
  healthBreakdown: {
    nutrition: 85,
    hydration: 68,
    sleep: 82,
    activity: 74,
    recovery: 80,
  },
  hydrationCurrent: 1400,
  hydrationGoal: 2200,
  caloriesCurrent: 1650,
  caloriesGoal: 2100,
  macros: {
    protein: { current: 85, goal: 120 },
    carbs: { current: 190, goal: 240 },
    fat: { current: 48, goal: 65 },
  },
  sleepDuration: '7h 45m',
  sleepRestfulPct: 82,
  stepsCurrent: 6420,
  stepsGoal: 8500,
};

export const INITIAL_QUESTS: DailyQuest[] = [
  {
    id: 'quest-1',
    title: 'Morning Hydration boost (500ml)',
    subtitle: 'Completed at 7:30 AM',
    xp: 10,
    completed: true,
    completedAt: '7:30 AM',
  },
  {
    id: 'quest-2',
    title: 'Log Lunch around 1:00 PM',
    subtitle: 'Balance carbs with lean protein',
    xp: 20,
    completed: false,
  },
  {
    id: 'quest-3',
    title: 'Beat the 2 PM Energy Slump',
    subtitle: 'Take a 5-min walk & consume your snack',
    xp: 30,
    completed: false,
  },
  {
    id: 'quest-4',
    title: 'Save 1 kitchen item before expiry',
    subtitle: 'Cook or freeze urgent produce',
    xp: 30,
    completed: false,
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Organic Bananas',
    category: 'Produce',
    quantity: 2,
    unit: 'pcs',
    location: 'Pantry Basket',
    expiresInDays: 0,
    statusBadge: 'Use Today!',
    isUrgent: true,
    emoji: '🍌',
  },
  {
    id: 'inv-2',
    name: 'Baby Spinach',
    category: 'Produce',
    quantity: 180,
    unit: 'g',
    location: 'Crisper Drawer',
    expiresInDays: 2,
    statusBadge: 'In 2 days',
    isUrgent: true,
    emoji: '🥬',
  },
  {
    id: 'inv-3',
    name: 'Greek Yogurt',
    category: 'Dairy & Protein',
    quantity: 1,
    unit: 'tub',
    location: 'Fridge Top Shelf',
    expiresInDays: 3,
    statusBadge: 'In 3 days',
    isUrgent: true,
    emoji: '🥛',
  },
  {
    id: 'inv-4',
    name: 'Fresh Paneer',
    category: 'Dairy & Protein',
    quantity: 200,
    unit: 'g',
    location: 'Fridge Deli Drawer',
    expiresInDays: 4,
    statusBadge: 'In 4 days',
    isUrgent: false,
    emoji: '🧀',
  },
  {
    id: 'inv-5',
    name: 'Rolled Oats',
    category: 'Pantry Staples',
    quantity: 500,
    unit: 'g',
    location: 'Aisle 2 Jar',
    expiresInDays: 60,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🌾',
  },
  {
    id: 'inv-6',
    name: 'Dark Roast Peanut Butter',
    category: 'Pantry Staples',
    quantity: 350,
    unit: 'g',
    location: 'Pantry Shelf 1',
    expiresInDays: 90,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🥜',
  },
  {
    id: 'inv-7',
    name: 'Raw Walnuts',
    category: 'Pantry Staples',
    quantity: 100,
    unit: 'g',
    location: 'Aisle 1 Bin',
    expiresInDays: 45,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🌰',
  },
  {
    id: 'inv-8',
    name: 'Chia Seeds',
    category: 'Pantry Staples',
    quantity: 150,
    unit: 'g',
    location: 'Spice Rack',
    expiresInDays: 120,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🌱',
  },
  {
    id: 'inv-9',
    name: 'Eggs (Free Range)',
    category: 'Dairy & Protein',
    quantity: 6,
    unit: 'pcs',
    location: 'Fridge Door',
    expiresInDays: 12,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🥚',
  },
  {
    id: 'inv-10',
    name: 'Avocado',
    category: 'Produce',
    quantity: 1,
    unit: 'pc',
    location: 'Fruit Bowl',
    expiresInDays: 2,
    statusBadge: 'In 2 days',
    isUrgent: false,
    emoji: '🥑',
  },
  {
    id: 'inv-11',
    name: 'Matcha Powder',
    category: 'Pantry Staples',
    quantity: 50,
    unit: 'g',
    location: 'Tea Drawer',
    expiresInDays: 180,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🍵',
  },
  {
    id: 'inv-12',
    name: 'Almonds',
    category: 'Pantry Staples',
    quantity: 250,
    unit: 'g',
    location: 'Snack Cabinet',
    expiresInDays: 75,
    statusBadge: 'Stable',
    isUrgent: false,
    emoji: '🫘',
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-1',
    title: 'Spinach & Paneer Power Bowl',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRbrdM4DM97biKUtshqEib7BBfmNDrSD1zRMSrzQQI_SACxOirbGTTzpRY7etBBMasBUsYokS7dChkP9OmR11JZWDMVOBr13azkfg7m2WiD6gWStkiXrQds1j6Oa2UZpIHphHAOCWOpovenSvPeQrJMRyRmQ_nQMyKKhG59wd91GWUFCRhmvpEocJE-RfyDetF5Ls55WK0_DxQ5YuxuF2UJ0gmmLK4XS5IdCAFQaX8T9YnAZHjMw-Prg',
    prepTimeMin: 12,
    calories: 410,
    proteinG: 28,
    staminaBenefit: '+3.8h Stamina • Prevents 2:15 PM dip',
    wasteSavedRupees: 90,
    usesExpiring: ['Baby Spinach', 'Paneer'],
    inStockPercent: 100,
    isWasteSaverNumber: 1,
    autoDeductItems: [
      { name: 'Baby Spinach', amount: '180g (all used!)', remainingStatus: 'Depleted' },
      { name: 'Fresh Paneer', amount: '120g', remainingStatus: '80g remaining' },
    ],
    description: 'Quick-sautéed spinach with golden seared paneer cubes, tossed in garlic and extra virgin olive oil.',
    instructions: [
      'Heat 1 tsp olive oil in a skillet over medium heat.',
      'Sear paneer cubes until light golden on all sides (3-4 mins).',
      'Fold in fresh baby spinach leaves and minced garlic until wilted.',
      'Season with sea salt, crushed black pepper, and serve hot.',
    ],
  },
  {
    id: 'rec-2',
    title: 'Blender Banana Peanut Oat Smoothie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUxdpuVFWsKEKOYNPvHvxErhlHLF0gA__0-ZWmgeQF9bzEL9I2gT1fiHI8MMSkRLkkIelXWv_X0zIFYTghrERYyl_9n3Ir1abVS5rwRp6m-8zVY8GEcnxYiE2R7l2T8oXhYNOGvc40qc62pFgTGJQ8FJFLZXYkTDs6XsdQ2S1JnpcaFbVVprhm-LXFiypPJnS_RzhoKSF5g-TyAq-2VrYmc9Obomiptpqkw7hrKFnTTEMfvjtg0ieDxg',
    prepTimeMin: 5,
    calories: 340,
    proteinG: 22,
    staminaBenefit: '+2.5h Focus • Pre-emptive 2:00 PM energy buffer',
    wasteSavedRupees: 65,
    usesExpiring: ['Organic Bananas', 'Greek Yogurt'],
    inStockPercent: 100,
    isWasteSaverNumber: 2,
    autoDeductItems: [
      { name: 'Organic Bananas', amount: '2 pcs (all used!)', remainingStatus: 'Depleted' },
      { name: 'Rolled Oats', amount: '40g', remainingStatus: '460g remaining' },
      { name: 'Peanut Butter', amount: '1 tbsp', remainingStatus: 'Stocked' },
    ],
    description: 'Thick, creamy restorative smoothie pairing ripe bananas with complex rolled oats and peanut butter.',
    instructions: [
      'Toss 2 sliced ripe bananas and 40g oats into high-speed blender.',
      'Add 2 tbsp Greek yogurt, 1 tbsp peanut butter, and 200ml cold water/ice.',
      'Pulse on high for 45 seconds until velvety smooth.',
      'Garnish with a pinch of cinnamon or chia seeds.',
    ],
  },
  {
    id: 'rec-3',
    title: 'Supercharged Greek Yogurt Bowl with Walnuts',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkvqM4cU6v0Wr-uwNM5HkI89LcfCQF-wsX4aMW2eA9BhIZNH1f84xteEyR8NjC4Jyb0j7ci_K6XnnZO1-bvE_udfCqHMMb0Kh6s3ZKFO3Rmv-U6-DNn_9-UiIDbDoy05CHYecm_KSwM_z_UFJmiNvv0_K6sVYVR2SYy0IuFFTaHhOVlaW5pkQgWoGy_g1JK8khEGm_T3pwuSAWES2XwTc07AtFGmCse88H_FryhwCsPo1NuIv7YeacZA',
    prepTimeMin: 4,
    calories: 310,
    proteinG: 24,
    staminaBenefit: '+3.0h Steady Glycemic Release',
    wasteSavedRupees: 75,
    usesExpiring: ['Greek Yogurt', 'Raw Walnuts'],
    inStockPercent: 100,
    autoDeductItems: [
      { name: 'Greek Yogurt', amount: '200g (all used!)', remainingStatus: 'Depleted' },
      { name: 'Raw Walnuts', amount: '20g', remainingStatus: '80g remaining' },
    ],
    description: 'Chilled Greek yogurt base drizzled with raw honey, chia seeds, and crushed roasted walnuts.',
    instructions: [
      'Spoon Greek yogurt into a chilled bowl.',
      'Top with coarsely cracked raw walnuts and chia seeds.',
      'Drizzle half a teaspoon of honey or maple syrup.',
      'Enjoy immediately as a metabolic stabilization fuel.',
    ],
  },
];

export const ENERGY_TIME_NODES: EnergyTimeNode[] = [
  {
    id: 'node-8a',
    code: '8A',
    time: '8:00 AM',
    energyPct: 85,
    status: 'Peak Performance',
    circadianPhase: 'Cortisol spike zenith',
    digestionState: 'Pre-breakfast basal',
    caffeineDecay: 'High (85mg absorbed)',
    hydrationDelta: 'Optimal (+100ml)',
  },
  {
    id: 'node-1030a',
    code: '10:30A',
    time: '10:30 AM',
    energyPct: 82,
    status: 'Stable Fuel',
    circadianPhase: 'Metabolic stabilization',
    digestionState: 'Oatmeal slow release',
    caffeineDecay: 'Peak receptor load',
    hydrationDelta: 'Hydrated',
  },
  {
    id: 'node-1230p',
    code: '12:30P',
    time: '12:30 PM',
    energyPct: 78,
    status: 'Digestive Load',
    circadianPhase: 'Thermic transit',
    digestionState: 'Active nutrient breakdown',
    caffeineDecay: 'Decaying (-30%)',
    hydrationDelta: 'Moderate',
  },
  {
    id: 'node-215p',
    code: '2:15P',
    time: '2:15 PM',
    energyPct: 52,
    status: 'Energy Slump Alert!',
    circadianPhase: 'Post-prandial drop phase',
    digestionState: 'Heavy glycogen shunt',
    caffeineDecay: 'Sub-threshold (-60%)',
    hydrationDelta: '-400ml deficit',
    isSlump: true,
  },
  {
    id: 'node-4p',
    code: '4P',
    time: '4:00 PM',
    energyPct: 68,
    status: 'Secondary Rise',
    circadianPhase: 'Post-slump arousal',
    digestionState: 'Gastric clearance',
    caffeineDecay: 'Residual trace',
    hydrationDelta: 'Rebounding',
  },
  {
    id: 'node-630p',
    code: '6:30P',
    time: '6:30 PM',
    energyPct: 80,
    status: 'Pre-Workout Surge',
    circadianPhase: 'Core temp peak',
    digestionState: 'Ready for light carb',
    caffeineDecay: 'Cleared',
    hydrationDelta: 'Target range',
  },
  {
    id: 'node-930p',
    code: '9:30P',
    time: '9:30 PM',
    energyPct: 60,
    status: 'Wind-Down',
    circadianPhase: 'Melatonin onset',
    digestionState: 'Dinner assimilation',
    caffeineDecay: 'Zero',
    hydrationDelta: 'Resting',
  },
];

export const SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    time: '08:00',
    period: 'AM',
    title: 'Morning Prep & Breakfast',
    description: 'Rolled oats, blueberries, whey isolate & chia',
    tag: 'Logged',
    colorBorder: 'bg-primary-container',
  },
  {
    time: '11:00',
    period: 'AM',
    title: 'College / Deep Focus Block',
    description: 'Hydration reminder: 500ml green tea triggered',
    colorBorder: 'bg-outline-variant',
    icon: 'water_drop',
  },
  {
    time: '01:00',
    period: 'PM',
    title: 'Scheduled Lunch',
    description: 'Turkey sweet potato bowl + mixed greens',
    tag: 'Macro Balanced',
    colorBorder: 'bg-secondary',
  },
  {
    time: '02:00',
    period: 'PM',
    title: 'Break & Energy Defense',
    description: 'Execute hydration + light snack to buffer slump',
    tag: 'Target Zone',
    colorBorder: 'bg-secondary',
  },
  {
    time: '06:00',
    period: 'PM',
    title: 'Workout: Cardio & HIIT',
    description: 'Recommendation: Light carb + BCAA pre-fuel at 5:15 PM',
    colorBorder: 'bg-primary-container',
    icon: 'fitness_center',
  },
  {
    time: '08:30',
    period: 'PM',
    title: 'Dinner',
    description: 'Recommends: High protein + magnesium for recovery',
    tag: 'Sleep Priming',
    colorBorder: 'bg-tertiary-fixed-dim',
  },
  {
    time: '10:45',
    period: 'PM',
    title: 'Sleep Wind-Down',
    description: 'Dim ambient lighting to < 30 lux, no blue spectrum',
    colorBorder: 'bg-outline',
    icon: 'bedtime',
  },
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'ai',
    text: "Hey Maya! 👋 I've ingested your morning biometrics and kitchen inventory. You've got a slight energy dip forecasted around 2:15 PM, and your bananas expire today. How can we optimize your afternoon?",
    time: '11:42 AM',
    subtext: 'Biometric sync complete',
  },
  {
    id: 'msg-2',
    sender: 'user',
    text: 'What should I eat before my 6 PM workout? And can I use anything expiring?',
    time: '11:43 AM',
  },
  {
    id: 'msg-3',
    sender: 'ai',
    text: "Here is your ideal pre-workout power booster using today's expiring items:",
    time: '11:43 AM',
    richCard: {
      recipeId: 'rec-2',
      title: 'Blender Banana Peanut Oat',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUxdpuVFWsKEKOYNPvHvxErhlHLF0gA__0-ZWmgeQF9bzEL9I2gT1fiHI8MMSkRLkkIelXWv_X0zIFYTghrERYyl_9n3Ir1abVS5rwRp6m-8zVY8GEcnxYiE2R7l2T8oXhYNOGvc40qc62pFgTGJQ8FJFLZXYkTDs6XsdQ2S1JnpcaFbVVprhm-LXFiypPJnS_RzhoKSF5g-TyAq-2VrYmc9Obomiptpqkw7hrKFnTTEMfvjtg0ieDxg',
      prepTime: 'Ready in 4 min',
      calories: 340,
      protein: '22g Protein',
      staminaTag: '+3.5h Stamina',
      wasteTag: 'Uses 2 Bananas',
      sustainedStaminaNote: 'Fast-acting glucose from ripe banana pairs with slow-burning oats for peak 6:00 PM HIIT block.',
      kitchenWinNote: 'Rescues ripe bananas scheduled to spoil at 8:00 PM tonight.',
      xpBonus: 15,
    },
  },
  {
    id: 'msg-4',
    sender: 'user',
    text: 'Why am I getting that 2:15 PM dip specifically?',
    time: '11:45 AM',
  },
  {
    id: 'msg-5',
    sender: 'ai',
    text: 'Your logged pasta lunch at 1:00 PM produces an insulin curve that coincides with your natural circadian dip at 2:15 PM.',
    time: '11:45 AM',
    subtext: 'Biometric simulation',
    trajectoryData: {
      dropPercent: 32,
      timeLabel: '2:15 PM (Slump)',
      solutionText: '350ml Cold Water + 8 Almonds',
      solutionDetail: 'Flattens afternoon glycemic spike by 65%',
      isMitigated: false,
    },
  },
];

export const INITIAL_TELEMETRY_EVENTS: TelemetryEvent[] = [
  {
    id: 'evt-1',
    name: 'meal_auto_deducted',
    details: 'Bananas + Greek Yogurt (Node #89214)',
    node: '#89214',
    timeAgo: 'Just now',
    type: 'deduct',
  },
  {
    id: 'evt-2',
    name: 'circadian_dip_prevented',
    details: '350ml hydration logged early',
    node: '#89215',
    timeAgo: '12s ago',
    type: 'prevent',
  },
  {
    id: 'evt-3',
    name: 'pulse_ai_query',
    details: '"What to cook before gym" (284ms)',
    node: '#89216',
    timeAgo: '45s ago',
    type: 'ai',
  },
  {
    id: 'evt-4',
    name: 'new_user_registered',
    details: 'Play Store organic attribution',
    node: '#89217',
    timeAgo: '1m ago',
    type: 'register',
  },
  {
    id: 'evt-5',
    name: 'ocr_receipt_processed',
    details: '6 items parsed locally in enclave (112ms)',
    node: '#89218',
    timeAgo: '2m ago',
    type: 'deduct',
  },
];

export const PRIVACY_SETTINGS: PrivacySetting[] = [
  {
    id: 'health_connect',
    title: 'Health Connect & Biometrics',
    description: 'Syncs step counts, resting heart rate, and sleep intervals for metabolic stamina curves.',
    enabled: true,
    icon: 'favorite',
    accentColor: '#00f59b',
  },
  {
    id: 'circadian_forecast',
    title: 'Circadian Energy Forecasting',
    description: 'Processes meal timings and past slumps to calculate your 2:15 PM dip risk curve locally.',
    enabled: true,
    icon: 'bolt',
    accentColor: '#ffb86b',
  },
  {
    id: 'pulse_ai_memory',
    title: 'Pulse AI Conversational Memory',
    description: 'Stores ingredients and past workout fuel preferences. Purged automatically every 30 days.',
    enabled: true,
    icon: 'smart_toy',
    accentColor: '#00f59b',
  },
  {
    id: 'pantry_ocr',
    title: 'On-Device Pantry OCR Scanner',
    description: 'Extracts grocery receipt items on your phone. Original photo files are purged immediately.',
    enabled: true,
    icon: 'photo_camera',
    accentColor: '#dfe2ee',
  },
  {
    id: 'anonymous_telemetry',
    title: 'Anonymous Crash Telemetry',
    description: 'Help engineering improve app stability. Stripped of all user identification before sending.',
    enabled: false,
    icon: 'analytics',
    accentColor: '#b9cbbd',
  },
];
